### ISSUE TITLE
gh-pages branch is not updated automatically

### ISSUE THREAD

**Issue by Valera** [CodyReichert/awesome-cl#418]
Hi! I noticed that automatic deploy to gh-pages no longer works and last deploy was at 1st June this year.

I think it due to some travis-ci related things, they have a message "Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on." Possibly you need to update old account or maybe create a new one for deploy to work.

**Comment by Valera** [comment]
That is, https://awesome-cl.com/ is slightly outdated now.

**Comment by vindarel** [comment]
Where do we do the changes? (I'm more used to Gitlab CI. I don't know if @CodyReichert  reads us (hello!))

Our travis.yml is this:

```
script:
  # Publish changes to https://awesome-cl.com
  - git clone --branch=gh-pages https://github.com/CodyReichert/awesome-cl dist
  - cp README.md dist/index.md
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
```
